/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.Controller;
import Database.Koneksi;
import javax.swing.JTable;

/**
 *
 * @author User
 */
public class Menu extends javax.swing.JFrame {

    Controller control;
    
    public Menu() {
        initComponents();
        Koneksi.getConnection();
        control = new Controller(this);
        control.isiTable();
        
        txtid.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button4 = new java.awt.Button();
        Header = new javax.swing.JPanel();
        itemHeader = new javax.swing.JLabel();
        Menu = new javax.swing.JPanel();
        lblid = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        lblnama = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        lbldeskripsi = new javax.swing.JLabel();
        txtjumlah = new javax.swing.JTextField();
        lbljumlah = new javax.swing.JLabel();
        lbljenis = new javax.swing.JLabel();
        txtjenis = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbldata = new javax.swing.JTable();
        simpan = new java.awt.Button();
        hapus = new java.awt.Button();
        edit = new java.awt.Button();
        reset = new java.awt.Button();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtdeskripsi = new javax.swing.JTextPane();

        button4.setLabel("button1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Header.setBackground(new java.awt.Color(0, 153, 204));
        Header.setLayout(new java.awt.BorderLayout());

        itemHeader.setFont(new java.awt.Font("Segoe UI Historic", 0, 24)); // NOI18N
        itemHeader.setForeground(new java.awt.Color(0, 0, 0));
        itemHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        itemHeader.setText("Data Barang");
        Header.add(itemHeader, java.awt.BorderLayout.CENTER);

        getContentPane().add(Header, java.awt.BorderLayout.PAGE_START);

        Menu.setBackground(new java.awt.Color(0, 102, 153));

        lblid.setBackground(new java.awt.Color(255, 255, 255));
        lblid.setForeground(new java.awt.Color(255, 255, 255));
        lblid.setText("Id");

        lblnama.setBackground(new java.awt.Color(255, 255, 255));
        lblnama.setForeground(new java.awt.Color(255, 255, 255));
        lblnama.setText("Nama");

        lbldeskripsi.setBackground(new java.awt.Color(255, 255, 255));
        lbldeskripsi.setForeground(new java.awt.Color(255, 255, 255));
        lbldeskripsi.setText("Deskripsi Barang");

        lbljumlah.setBackground(new java.awt.Color(255, 255, 255));
        lbljumlah.setForeground(new java.awt.Color(255, 255, 255));
        lbljumlah.setText("Jumlah");

        lbljenis.setBackground(new java.awt.Color(255, 255, 255));
        lbljenis.setForeground(new java.awt.Color(255, 255, 255));
        lbljenis.setText("Jenis");

        txtjenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Peralatan Dapur", "Makanan", "Peralatan Kamar Mandi", " ", " ", " ", " " }));

        tbldata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Nama", "Jenis", "Jumlah", "Deskripsi"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbldata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbldataMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbldata);
        if (tbldata.getColumnModel().getColumnCount() > 0) {
            tbldata.getColumnModel().getColumn(0).setResizable(false);
            tbldata.getColumnModel().getColumn(0).setPreferredWidth(5);
            tbldata.getColumnModel().getColumn(1).setResizable(false);
            tbldata.getColumnModel().getColumn(2).setResizable(false);
            tbldata.getColumnModel().getColumn(3).setResizable(false);
            tbldata.getColumnModel().getColumn(3).setPreferredWidth(25);
            tbldata.getColumnModel().getColumn(4).setResizable(false);
            tbldata.getColumnModel().getColumn(4).setPreferredWidth(150);
        }

        simpan.setActionCommand("simpan");
        simpan.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        simpan.setLabel("Simpan");
        simpan.setName(""); // NOI18N
        simpan.setPreferredSize(new java.awt.Dimension(60, 25));
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        hapus.setActionCommand("hapus");
        hapus.setLabel("Hapus");
        hapus.setMinimumSize(new java.awt.Dimension(60, 35));
        hapus.setPreferredSize(new java.awt.Dimension(60, 25));
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        edit.setActionCommand("edit");
        edit.setLabel("Edit");
        edit.setMinimumSize(new java.awt.Dimension(60, 35));
        edit.setPreferredSize(new java.awt.Dimension(60, 25));
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        reset.setActionCommand("reset");
        reset.setLabel("Reset");
        reset.setMinimumSize(new java.awt.Dimension(60, 35));
        reset.setName(""); // NOI18N
        reset.setPreferredSize(new java.awt.Dimension(60, 25));
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(txtdeskripsi);

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblid, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(lbldeskripsi))
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblnama, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbljenis, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbljumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtnama, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(txtjumlah)
                            .addComponent(txtjenis, 0, 1, Short.MAX_VALUE))
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblid)
                            .addComponent(lbldeskripsi))))
                .addGap(6, 6, 6)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblnama)
                        .addGap(46, 46, 46)
                        .addComponent(lbljumlah))
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtjenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbljenis))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtjumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(simpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        simpan.getAccessibleContext().setAccessibleName("Simpan");
        simpan.getAccessibleContext().setAccessibleDescription("");
        hapus.getAccessibleContext().setAccessibleName("hapus");
        edit.getAccessibleContext().setAccessibleName("edit");
        reset.getAccessibleContext().setAccessibleName("reset");

        getContentPane().add(Menu, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        control.delete();
        control.isiTable();
        control.reset();
    }//GEN-LAST:event_hapusActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        control.insert();
        control.isiTable();
        control.reset();
    }//GEN-LAST:event_simpanActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        control.update();
        control.isiTable();
        control.reset();
    }//GEN-LAST:event_editActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        control.reset();
    }//GEN-LAST:event_resetActionPerformed

    private void tbldataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbldataMouseClicked
        int row = tbldata.getSelectedRow();
        control.isianForm(row);
    }//GEN-LAST:event_tbldataMouseClicked


    public int getId(){
        return Integer.parseInt(txtid.getText());
    }
    
    public String getNama(){
        return txtnama.getText();
    }
    
    public String getJenis(){
        return (String)txtjenis.getSelectedItem();
    }
    
    public int getJumlah(){
        return Integer.parseInt(txtjumlah.getText());
    }
    
    public String getDeskripsi(){
        return txtdeskripsi.getText();
    }
    
    public void setId(int id)
    {
        if(id == 0){
            txtid.setText("");
        } else {
            txtid.setText(Integer.toString(id));
        }
    }
    
    public void setNama(String nama)
    {
        txtnama.setText(nama);
    }
    
    public void setJenis(String jenis)
    {
        txtjenis.setSelectedItem(jenis);
    }
    
    public void setJumlah(int jumlah)
    {
        txtjumlah.setText(Integer.toString(jumlah));
    }
    
    public void setDeskripsi(String deskripsi)
    {
        txtdeskripsi.setText(deskripsi);
    }
    
    public JTable getTabel(){
        return tbldata;
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Menu;
    private java.awt.Button button4;
    private java.awt.Button edit;
    private java.awt.Button hapus;
    private javax.swing.JLabel itemHeader;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbldeskripsi;
    private javax.swing.JLabel lblid;
    private javax.swing.JLabel lbljenis;
    private javax.swing.JLabel lbljumlah;
    private javax.swing.JLabel lblnama;
    private java.awt.Button reset;
    private java.awt.Button simpan;
    private javax.swing.JTable tbldata;
    private javax.swing.JTextPane txtdeskripsi;
    private javax.swing.JTextField txtid;
    private javax.swing.JComboBox<String> txtjenis;
    private javax.swing.JTextField txtjumlah;
    private javax.swing.JTextField txtnama;
    // End of variables declaration//GEN-END:variables
}
